Return-Path: <linux-rtc-owner@vger.kernel.org>
X-Original-To: lists+linux-rtc@lfdr.de
Delivered-To: lists+linux-rtc@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id 6E45A7F4F8
	for <lists+linux-rtc@lfdr.de>; Fri,  2 Aug 2019 12:24:51 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S2390829AbfHBKYn (ORCPT <rfc822;lists+linux-rtc@lfdr.de>);
        Fri, 2 Aug 2019 06:24:43 -0400
Received: from atrey.karlin.mff.cuni.cz ([195.113.26.193]:43479 "EHLO
        atrey.karlin.mff.cuni.cz" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S1730941AbfHBKYn (ORCPT
        <rfc822;linux-rtc@vger.kernel.org>); Fri, 2 Aug 2019 06:24:43 -0400
Received: by atrey.karlin.mff.cuni.cz (Postfix, from userid 512)
        id DB30980355; Fri,  2 Aug 2019 12:24:27 +0200 (CEST)
Date:   Fri, 2 Aug 2019 12:24:39 +0200
From:   Pavel Machek <pavel@ucw.cz>
To:     linux-rtc@vger.kernel.org, Alessandro Zummo <a.zummo@towertech.it>,
        Alexandre Belloni <alexandre.belloni@bootlin.com>,
        linux-kernel@vger.kernel.org, syzkaller-bugs@googlegroups.com
Subject: Re: Reminder: 1 open syzbot bug in rtc subsystem
Message-ID: <20190802102439.GA29677@amd>
References: <20190724025008.GL643@sol.localdomain>
 <20190728132332.GB8718@xo-6d-61-c0.localdomain>
 <20190731022707.GC687@sol.localdomain>
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha1;
        protocol="application/pgp-signature"; boundary="Qxx1br4bt0+wmkIi"
Content-Disposition: inline
In-Reply-To: <20190731022707.GC687@sol.localdomain>
User-Agent: Mutt/1.5.23 (2014-03-12)
Sender: linux-rtc-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-rtc.vger.kernel.org>
X-Mailing-List: linux-rtc@vger.kernel.org


--Qxx1br4bt0+wmkIi
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable

On Tue 2019-07-30 19:27:07, Eric Biggers wrote:
> On Sun, Jul 28, 2019 at 03:23:33PM +0200, Pavel Machek wrote:
> > On Tue 2019-07-23 19:50:08, Eric Biggers wrote:
> > > [This email was generated by a script.  Let me know if you have any s=
uggestions
> > > to make it better, or if you want it re-generated with the latest sta=
tus.]
> > >=20
> > > Of the currently open syzbot reports against the upstream kernel, I'v=
e manually
> > > marked 1 of them as possibly being a bug in the rtc subsystem.
> > >=20
> > > If you believe this bug is no longer valid, please close the syzbot r=
eport by
> > > sending a '#syz fix', '#syz dup', or '#syz invalid' command in reply =
to the
> > > original thread, as explained at https://goo.gl/tpsmEJ#status
> > >=20
> > > If you believe I misattributed this bug to the rtc subsystem, please =
let me
> > > know, and if possible forward the report to the correct people or mai=
ling list.
> > >=20
> > > Here is the bug:
> >=20
> >=20
> > Can you stop spamming lkml?
> >=20
> > Sending 20 "reminders" in a row is not something human would do, and it=
 is not
> > something your bot should be allowed to do, either.
> >=20
>=20
> Hi Pavel, just to clarify, though I used a script to generate these email=
s, I
> manually reviewed and sent each one; I also manually assigned the subsyst=
ems and
> sanity checked the bisection results.  (I'm also not on the syzbot team. =
 I just
> care about the security and reliability of the Linux kernel...)  The reas=
on
> there are so many of these emails is that there are a lot of kernel subsy=
stems
> with open bug reports, many clearly still valid -- even considering that I
> decided to skip some subsystems after deciding to just fix the bugs mysel=
f,
> update the bug statuses myself, send some other email, or just wait.
>=20
> I suppose there's some argument to be made that it's too noisy to Cc
> linux-kernel when I've already assigned a subsystem, though, so I'll try
> dropping linux-kernel from Cc for next time and just using the subsystem =
list
> and maintainers, and see if that goes any better or worse.

That should do the trick. Thanks!

> Note that the syzbot reports themselves are still going to linux-kernel, =
though.

Yes, I know. I'm not entirely sure that is good idea.

									Pavel
--=20
(english) http://www.livejournal.com/~pavelmachek
(cesky, pictures) http://atrey.karlin.mff.cuni.cz/~pavel/picture/horses/blo=
g.html

--Qxx1br4bt0+wmkIi
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: Digital signature

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAl1ED2YACgkQMOfwapXb+vIueQCguHwb6twaVho51dNDt9htIUGs
aQwAoMIK2npDdI7S60cvc1VXN2zWACBg
=aCxV
-----END PGP SIGNATURE-----

--Qxx1br4bt0+wmkIi--
